#! /bin/bash

# Distributed under the terms of the BSD 3-Clause license

# Usage:
# "flash" - print all files with their numbers and sizes
# "flash <num>" - print file <num>
# "flash <num> <prog> [<args...>]" - open file <num> with program <prog>

if [ -n "$1" ]; then
    want="$1"
    shift
fi

pgrep -f libflashplayer.so | while read pid; do
    ls -l /proc/$pid/fd/* | grep -io '\/.* /tmp/flash[[:alnum:]]\{8\}' | while read line; do
        fn=$(echo "$line" | cut -d" " -f1)
        num=$(basename "$fn")

        if [ -z "$want" ] || [ "$want" = "$num" ]; then
            if [ -z "$1" ]; then
                echo $num $(du -hL "$fn" | cut -f1)
            else
                "$@" "$fn"
            fi
        fi
    done
done
