#! /bin/bash

# Distributed under the terms of the BSD 3-Clause license

# Usage:
# "until-success <wait> <cmd> [<args...>]" - run "<cmd> [<args...>]" every
#                                            <wait> seconds until it succeeds

n="$1"
prog="$2"
shift 2
while true; do
    "$prog" "$@" && break
    n=$[n-1]
    echo "failed; $n attempts remaining"
    [ "$n" -eq 0 ] && break
done
