#!/bin/bash

# Distributed under the terms of the BSD 3-Clause license

# Usage:
# "uzbl-tabbed-open [<uris...>]" - open uris in existing uzbl-tabbed instance
#                                  or in a new one

# use any uzbl to reach the event manager
fifo="$(find /tmp -user "$UID" -name 'uzbl_fifo_*' 2> /dev/null | tail -n 1)"
if [ -p "$fifo" ]; then
    for uri in "$@"; do
        echo "event new_tab $uri" > "$fifo"
    done
    echo "event bring_to_front" > "$fifo"
else
    exec uzbl-tabbed "$@"
fi
