#! /usr/bin/env python2

# ytsubs 0.2.2

# Distributed under the terms of the GNU General Public License, version 3

# Requires the gdata-python-client (Python 2):
# http://code.google.com/p/gdata-python-client/

# Usage:
# "ytsubs <username> [<password>]" - omit password to type it in without echo

# Prints the RSS feed to stdout (pipe it to a file or something).  At the
# moment, videos are restricted to those published in the last 2 weeks.

# TODO:
# - nicer descriptions (wrap in a <pre>)
# - doesn't work for 'shows'?

import sys
import socket
import time
from signal import signal, SIGINT, SIGTERM
from getpass import getpass
from xml.etree.ElementTree import XML, tostring as xml_to_string
from xml.sax.saxutils import escape as escape_xml
import urlparse
from urllib import urlencode

from gdata.youtube.service import YouTubeService
from gdata import service as gservice

YT_DATE_FORMAT = '%Y-%m-%dT%H:%M:%S.000Z'
FEED_DATE_FORMAT = '%a, %d %b %Y %H:%M:%S %Z'
FEED_TEMPLATE = '''<?xml version="1.0"?>
<rss version="2.0">
    <channel>
        <title>YouTube subscriptions</title>
        <link>https://www.youtube.com/my_subscriptions</link>
        <docs>http://blogs.law.harvard.edu/tech/rss</docs>
        <lastBuildDate>{0}</lastBuildDate>
    </channel>
</rss>'''


def err (s):
    print >> sys.stderr, s


def login (user, pwd):
    yt = YouTubeService()
    yt.email = user
    yt.password = pwd
    try:
        yt.ProgrammaticLogin()
    except gservice.BadAuthentication:
        return None
    else:
        return yt


def get_vids (yt, earliest):
    subs = yt.GetYouTubeSubscriptionFeed().entry
    uri = 'http://gdata.youtube.com/feeds/api/users/{0}/uploads?' \
          'start-index={1}'
    vids = []
    for sub in subs:
        name = sub.username.text
        err(name)
        this_vids = []
        feed = None
        while not this_vids or \
              time.strptime(this_vids[-1].published.text, YT_DATE_FORMAT) < \
              earliest:
            # request more until we have all we want or every video
            this_uri = uri.format(name, len(this_vids) + 1)
            if feed is not None:
                this_uri += '&max-results=' + feed.items_per_page.text
            feed = yt.GetYouTubeVideoFeed(this_uri)
            this_vids += feed.entry
            if len(this_vids) == int(feed.total_results.text):
                # no more videos
                break
        for v in this_vids:
            t = time.mktime(time.strptime(v.published.text, YT_DATE_FORMAT))
            if t < earliest:
                break
            vids.append((t, v, name))
    vids.sort(reverse = True)
    return vids


def mk_feed (vids):
    xml = XML(FEED_TEMPLATE.format(time.strftime(FEED_DATE_FORMAT,
                                                 time.localtime())))
    channel = xml[0]
    for t, v, sub in vids:
        title = '{0}: \'{1}\''.format(sub, v.title.text)
        guid = url = v.link[0].href
        # remove all query string items from URL except video ID
        url = urlparse.urlsplit(url)
        qs = url.query
        url = list(url)
        url[url.index(qs)] = urlencode({'v': urlparse.parse_qs(qs)['v'][0]})
        url = urlparse.urlunsplit(url)
        # add as RSS item
        args = (title, url, v.content.text,
                time.strftime(FEED_DATE_FORMAT, time.localtime(t)), guid)
        s = '''
        <item>
            <title>{0}</title>
            <link>{1}</link>
            <description>{2}</description>
            <pubDate>{3}</pubDate>
            <published>{3}</published>
            <guid>{4}</guid>
        </item>'''.format(*(escape_xml(arg) for arg in args))
        channel.append(XML(s))
    # update build time
    return xml_to_string(xml)


if __name__ == '__main__':
    # handle signals
    quit = lambda *args: sys.exit(0)
    signal(SIGINT, quit)
    signal(SIGTERM, quit)
    # get details
    if len(sys.argv) <= 1:
        err('error: expected username argument')
        sys.exit(1)
    elif len(sys.argv) <= 2:
        pwd = getpass()
    else:
        pwd = sys.argv[2]
    # do the stuff
    try:
        yt = login(sys.argv[1], pwd)
        if yt is None:
            err('error: can\'t log in')
            sys.exit(1)
        vids = get_vids(yt, time.time() - 60 * 60 * 24 * 7 * 2)
    except socket.gaierror:
        err('error: can\'t connect to the YouTube service')
        sys.exit(1)
    print mk_feed(vids)
